#!/bin/bash

set -e

cryptolfile=$1
func=$2

cat > sawcmds.saw <<- EOM
m <- cryptol_load "$cryptolfile";
f <- cryptol_extract m "$func";
write_aig "${func}.aig" f;
EOM

cat > abccmds.abc <<- EOM
read "${func}.aig"
dsd
strash
multi
fraig
rewrite -l
balance -s -d -x
write_verilog "${func}.v"
EOM

cat > yosys.ys <<- EOM
read_verilog "${func}.v"
synth -run fine
techmap; opt -fast
dfflibmap -liberty gc_cells.lib
abc -liberty gc_cells.lib
clean
write_verilog ${func}.v
EOM

saw sawcmds.saw
abc -f abccmds.abc
yosys yosys.ys
