#!/bin/bash

for ty in C2A C2C; do 
    for f in aes1r b0 b0_64 b0_32 b0_16 b0_8 b0_7 b0_6 b0_5 b0_4 b0_3 b0_2 sbox_ linearParts; do 
        ./scripts/latex-info $ty cryptol/AES.cry $f; 
    done
done

cabal run --verbose=0 -- -C aes
for f in aes1r b0 b0_64 b0_32 b0_16 b0_8 b0_7 b0_6 b0_5 b0_4 b0_3 b0_2 sbox; do
    ./scripts/latex-info DSL src/Circuits/Aes.hs $f
done
