#!/bin/bash

set -e

cryptolfile=$(realpath $1)
func=$2
libertyfile=$(realpath $3)

mkdir -p work
cd work

cat > sawcmds.saw <<- EOM
m <- cryptol_load "$cryptolfile";
f <- cryptol_extract m "$func";
write_aig "${func}.aig" f;
EOM

cat > abccmds.abc <<- EOM
read "${func}.aig"
dsd
strash
multi
fraig
rewrite -l
balance -s -d -x
write_verilog "${func}.v"
EOM

cat > yosys.ys <<- EOM
read_verilog "${func}.v"
synth -run fine
techmap; opt -fast
dfflibmap -liberty ${libertyfile}
abc -liberty ${libertyfile}
write_verilog ${func}.v
EOM

#saw sawcmds.saw > /dev/null
#abc -f abccmds.abc > /dev/null
#yosys yosys.ys > /dev/null

saw sawcmds.saw
abc -f abccmds.abc
yosys yosys.ys
