#!/bin/bash

set -e

cryptolfile=$(realpath $1)
func=$2

scriptdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# libertyfile=$(realpath $3)
libertyfile=$scriptdir/../liberties/aig.lib

mkdir -p work
cd work

cat > sawcmds.saw <<- EOM
m <- cryptol_load "$cryptolfile";
f <- cryptol_extract m "$func";
write_aig "${func}.aig" f;
EOM

cat > abccmds.abc <<- EOM
read "${func}.aig"
dsd
strash
multi
fraig
rewrite -l
balance -s -d -x
write_verilog "${func}.in.v"
EOM

# cat > yosys.ys <<- EOM
# read_verilog "${func}.in.v"
# write_verilog ${func}.out.v
# EOM

cat > yosys.ys <<- EOM
read_verilog "${func}.in.v"
synth -run fine
techmap; opt -fast
dfflibmap -liberty ${libertyfile}
abc -liberty ${libertyfile}
write_verilog ${func}.out.v
EOM

# saw sawcmds.saw 
# abc -f abccmds.abc
# yosys yosys.ys

sizes=($(egrep "$func\\s*:\\s*" $cryptolfile | perl -ne '/\(\[(\d+)],\s*\[(\d+)\]\)/; print "$1 $2";'))
inputsize=${sizes[0]}
keysize=${sizes[1]}

saw sawcmds.saw > /dev/null
abc -f abccmds.abc > /dev/null
yosys yosys.ys > /dev/null

python $scriptdir/verilog2acirc.py $func.out.v $keysize
