#!/bin/bash

begin_table() {
    cat <<- EOF
	\\begin{center}
	\\begin{tabular}{| l || c | c | c | c | c | c | c | c | c | c |}
	\\hline
	object & mode & nin & nkey & nout & size & \\#\\textsc{mul} & depth & degree & Zim-$\\kappa$ & Lin-$\\kappa$ \\\\
	\\hline
	EOF
}

end_table() {
    cat <<- EOF
	\\end{tabular}
	\\end{center}
	EOF
    echo
}

for ty in C2A C2C; do
    begin_table
    for f in aes1r b0 b0_64 b0_32 b0_16 b0_8 b0_7 b0_6 b0_5 b0_4 b0_3 b0_2 sbox_ linearParts; do
        ./scripts/latex-info $ty cryptol/AES.cry $f;
    done
    end table
done

cabal run --verbose=0 -- -C aes
begin_table
for f in aes1r b0 b0_64 b0_32 b0_16 b0_8 b0_7 b0_6 b0_5 b0_4 b0_3 b0_2 sbox; do
    ./scripts/latex-info DSL src/Circuits/Aes.hs $f;
done


for ty in C2A C2C; do
    begin_table
    for f in prg_16_16 prg_16_32 prg_16_48 prg_16_64 prg_32_32 prg_32_64 prg_32_96 prg_32_128; do
        ./scripts/latex-info $ty cryptol/goldreich.cry $f;
    done
    end_table
done

cabal run --verbose=0 -- -C goldreich
begin_table
for f in prg_16_16 prg_16_32 prg_16_48 prg_16_64 prg_32_32 prg_32_64 prg_32_96 prg_32_128; do
    ./scripts/latex-info DSL src/Circuits/Goldreich.hs $f;
done
end_table


cabal run --verbose=0 -- -C ggm
begin_table
for f in ggm_1_16 ggm_2_16 ggm_3_16 ggm_4_16 ggm_1_32 ggm_2_32 ggm_3_32 ggm_4_32; do
    ./scripts/latex-info DSL src/Circuits/Goldreich.hs $f;
done
end_table

begin_table
for f in ggm_rachel_1_16 ggm_rachel_2_16 ggm_rachel_3_16 ggm_rachel_4_16 ggm_rachel_1_32 ggm_rachel_2_32 ggm_rachel_3_32 ggm_rachel_4_32; do
    ./scripts/latex-info DSL src/Circuits/Goldreich.hs $f 16;
done
end_table

for ty in C2A C2C; do
    begin_table
    for f in f1_16 f1_32 f1_64 f1_128; do
        ./scripts/latex-info $ty cryptol/applebaum.cry $f;
    done
    end_table
done

cabal run --verbose=0 -- -C applebaum
begin_table
for f in f1_16 f1_32 f1_64 f1_128; do
    ./scripts/latex-info DSL src/Circuits/Goldreich.hs $f;
done
end_table
