#!/bin/bash

case $1 in
    c2a )
        ty=C2A
        res=$3.cry.acirc
        ./scripts/cryptol2acirc $2 $3 > $res
        ;;
esac

line=$(cabal run --verbose=0 -- -l $res)
line=${line/\#1/$3}
line=${line/\#2/$ty}
line=${line/\#3/$(grep -c MUL $res)}
echo $line
